_target_: src.models.transformer_apo.TransformerAPOModel

d_model: 8                
num_heads: 2             
d_hidden: 32            
num_blocks: 2            
lr: 0.0001               
epochs: 3000            
batch_size: 256         
use_minibatch: false     
verbose: false          
loss_type: ce           